classDiagram
    BasePodcastParser <|-- PythonBytesParser
    BasePodcastParser <|-- OtherParser
    BasePodView <|-- PythonistaPodView
    main <-- PythonistaPodView
    main <-- BasePodcastParser

class BasePodcastParser {
    <<abstract>>
    +try_all()
    }

class PythonBytesParser {
    + base_url
    - get_podcast_short_name() : str
    - get_current_episode_number() : int
    + parse() : List[Url]
    }

class OtherParser {
    + base_url
    - get_podcast_short_name() : str
    - get_current_episode_number() : int
    + parse() : List[Url]
    }

class BasePodView {
    <<abstract>>
    +show(urls: List[Url])
    add_urls_to_reminder(urls: List[Url])
    get_option(self, options: List[str], title='')
}

class PythonistaPodView {
    ...
}

class main {
    ...
}